version: '3'

services: 
  gateway-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flaskblog-backend
    command: bash -c "pip3 install -r requirements.txt && export FLASK_APP=index.py && flask run --host=0.0.0.0"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - flask-redis
    ports:
      - "5000:5000"
    volumes:
      - .:/code

  # gateway-mysqldb:
  #   image: mysql:5.7
  #   container_name: gateway-mysqldb
  #   restart: always
  #   ports:
  #     - 3001:3306
  #   environment: 
  #     MYSQL_DATABASE: gateway_db
  #     MYSQL_ROOT_PASSWORD: password

  flask-redis:
    image: redis:4
    container_name: flask-redis
    ports:
      - 5002:6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  # gateway-phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:4.7
  #   container_name: gateway-phpmyadmin
  #   restart: always
  #   ports:
  #     - 3003:80
  #   environment:
  #     PMA_ARBITRARY: 1
  #   volumes:
  #     - /sessions